export const ADD_TASK_START = 'ADD_TASK_START';
export const ADD_TASK_SUCESS = 'ADD_TASK_SUCESS';
export const ADD_TASK_ERROR = 'ADD_TASK_ERROR';


export const DELETE_TASK_START = 'DELETE_TASK_START';
export const DELETE_TASK_SUCESS = 'DELETE_TASK_SUCESS';
export const DELETE_TASK_ERROR = 'DELETE_TASK_ERROR';


export const UPDATE_TASK_START = 'UPDATE_TASK_START';
export const UPDATE_TASK_SUCESS = 'UPDATE_TASK_SUCESS';
export const UPDATE_TASK_ERROR = 'UPDATE_TASK_ERROR';

